#lang racket/base
(require pop-pl/current/constants
         "harness.rkt")

(prescription-test
 "../examples/heparin/heprin.pop"
 (=> start 
     (givebolus (n 80 units/kg) heparin iv)
     (start (n 18 units/kg/hour) heparin iv)
     (checkaptt))
 (=> (apttresult 40)
     (givebolus (n 80 units/kg) heparin iv)
     (increase heparin (n 3 units/kg/hour)))
 (=> (advance 7 hours)
     (checkaptt))
 (=> (apttresult 120)
     (decrease heparin (n 1 unit/kg/hour)))
 (=> (advance 7 hours)
     (checkaptt))
 (=> (apttresult 80))
 (=> (advance 7 hours)
     (checkaptt))
 (=> (apttresult 80))
 (=> (advance 8 hours))
 (=> (advance 16 hours)
     (checkaptt))
 (=> (apttresult 80))
 (=> (advance 24 hours)
     (checkaptt))
 (=> (apttresult 3000)
     (hold heparin))
 (=> (advance 2 hour)
     (restart heparin)
     (decrease heparin (n 3 units/kg/hour)))
 (=> (advance 5 hours)
     (checkaptt))
 (=> (apttresult 80))
 (=> (advance 6 hours)
     (checkaptt))
 (=> (apttresult 80))
 (=> (advance 8 hours))
 (=> (advance 16 hours)
     (checkaptt)))
