#lang racket/base
(require pop-pl/current/constants
         "harness.rkt")

(prescription-test
 "../examples/heparin/heprin.pop"
 (=> start 
     (givebolus _ heparin "iv")
     (start _ heparin "iv")
     (checkptt))
 (=> (ptt 40)
     (givebolus _ heparin "iv")
     (increase heparin _))
 (=> (advance 7 hours)
     (checkptt))
 (=> (ptt 120)
     (decrease heparin (n -1 unit/kg/hour)))
 (=> (advance 7 hours)
     (checkptt))
 (=> (ptt 80))
 (=> (advance 7 hours)
     (checkptt))
 (=> (ptt 80))
 (=> (advance 8 hours))
 (=> (advance 16 hours)
     (checkptt))
 (=> (ptt 80))
 (=> (advance 24 hours)
     (checkptt))
 (=> (ptt 3000)
     (hold heparin))
 (=> (advance 2 hour)
     (restart heparin)
     (decrease heparin _))
 (=> (advance 5 hours)
     (checkptt))
 (=> (ptt 80))
 (=> (advance 6 hours)
     (checkptt))
 (=> (ptt 80))
 (=> (advance 8 hours))
 (=> (advance 16 hours)
     (checkptt)))
